# Generated by Django 3.1.5 on 2021-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadmembro',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
    ]
