# Generated by Django 3.1.5 on 2021-01-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadmembro',
            old_name='phone_namber',
            new_name='phone_number',
        ),
    ]
